title: ruebe5w
description: "Persöhnlicher Blog"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/chris_quad.jpg"

# Social Links
email: christopher@bongert.eu
github_username: ruebe5w
mastodon_username: ruebe5w


# External API
giscus_repo: "ruebe5w/ruebe5w.github.io"
giscus_repoId: "R_kgDOM4e7VA"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOM4e7VM4Ci4GJ"
goatcounter_code: ruebe5w
#google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl: https://ruebe5w.github.io

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
#  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
